# Generated by Django 4.2 on 2025-05-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
